import "equal-experts/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "equal-experts/trpc/react";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="ee-background-grey">
        <a href="https://www.equalexperts.com/">
          <header className="ee-background-blue h-18 p-4">
            <img
              src="/equalexperts.svg"
              alt="[=] Equal Experts"
              width={"150px"}
              height={"40px"}
            />
          </header>
        </a>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
